import Footer from "@/component/Footer"
import Navbar from "@/component/Navbar"
import { Metadata } from "next"
import React, { Suspense } from "react";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Wellcom | xinchao",
    template: "%s | xinchao",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
