import Footer from "@/component/Footer"
import Navbar from "@/component/Navbar"
import { Metadata } from "next"
import React, { Suspense } from "react";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Wellcom | xinchao",
    template: "%s | xinchao",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f6e9d5]">
        <div className="fixed top-0 left-0 right-0 z-50 bg-white">
          <Navbar />
        </div>
        <div className="pt-16">
          {" "}
          {/* Add padding-top to account for fixed navbar */}
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        </div>
        <Footer />
      </body>
    </html>
  );
}
