import Footer from "@/component/Footer"
import Navbar from "@/component/Navbar"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Wellcom | xinchao",
    template: "%s | xinchao",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  )
}
