// src/layouts/RootLayout.tsx

import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";
import { Metadata } from "next";
import Header from "@/component/SideBar";
import { ReactNode } from "react"; // Import ReactNode

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Wellcom | xinchao",
    template: "%s | xinchao",
  },
  description: "Generated by Next.js",
};

// Define your custom props type
interface RootLayoutProps {
  children: ReactNode; // Only include children prop
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Navbar />
        <div className="flex p-4 justify-center">
          <div className="flex p-4 w-1/4">
            <Header />
          </div>

          <div className="flex p-4 w-full">
            <main className="flex-1 border border-gray-300 rounded-lg p-2">
              {children}
            </main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
