// src/layouts/RootLayout.tsx

import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";
import { Metadata } from "next";
import Header from "@/component/Header";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Wellcom | xinchao",
    template: "%s | xinchao",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Navbar />
        <div className="flex p-4 justify-center">
          <div className="flex p-4">
            <Header />
          </div>

          <div className="flex p-4">
            <main className="flex-1 border border-gray-300 rounded-lg p-2">
              {children}
            </main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
